<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>EnecaDataGrid</AssemblyName>
    <RootNamespace>EnecaDataGrid</RootNamespace>
    <Product>EnecaDataGrid</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\windows-library-ui\EnecaUI3\EnecaUI3.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <Page Remove="artifacts\**\*.xaml" />
    <EmbeddedResource Remove="artifacts\**\*" />
    <None Remove="artifacts\**\*" />
  </ItemGroup>

</Project>
